version: '3.8'

services:
  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: virallens-server
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${SERVER_PORT:-5000}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    ports:
      - "${SERVER_PORT:-5000}:${SERVER_PORT:-5000}"
    networks:
      - virallens-network
    volumes:
      - ./server/src:/app/src
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${SERVER_PORT:-5000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000/api}
    container_name: virallens-client
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT:-3000}:80"
    depends_on:
      - server
    networks:
      - virallens-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  virallens-network:
    driver: bridge

